#!/bin/bash
sudo yum -y update
sudo yum -y install httpd
sudo systemctl enable httpd
sudo systemctl start httpd
sudo echo “<html><body><h1>Brian’s AWS Week 9 Project! 3-Tier Architecture! </h1></body></html>” > /var/www/html/index.html
